src/src/Entity/Comment.php
<?php
declare(strict_types=1);

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommentRepository::class)]
class Comment
{
    const REDDIT_URL_FORMAT = 'https://www.reddit.com/r/%s/comments/%s/comment/%s/';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 25)]
    private $author;

    #[ORM\Column(type: 'integer', options: ['default' => 0])]
    private $score;

    #[ORM\Column(type: 'string', length: 10, unique: true)]
    private $redditId;

    #[ORM\ManyToOne(targetEntity: self::class, cascade: ['persist', 'remove'], inversedBy: 'replies')]
    #[ORM\JoinColumn(onDelete: 'SET NULL')]
    private $parentComment;

    #[ORM\OneToMany(mappedBy: 'parentComment', targetEntity: self::class, cascade: ['persist', 'remove'])]
    private $replies;

    #[ORM\ManyToOne(targetEntity: Post::class, inversedBy: 'comments')]
    #[ORM\JoinColumn(nullable: false)]
    private $parentPost;

    #[ORM\Column(type: 'integer', options: ['default' => 0])]
    private $depth;

    #[ORM\OneToOne(mappedBy: 'comment', targetEntity: Content::class, cascade: ['persist', 'remove'])]
    private $content;

    #[ORM\OneToMany(mappedBy: 'comment', targetEntity: CommentAuthorText::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private $commentAuthorTexts;

    #[ORM\OneToMany(mappedBy: 'comment', targetEntity: CommentAward::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    private $commentAwards;

    #[ORM\Column(type: 'text')]
    private $redditUrl;

    #[ORM\OneToMany(mappedBy: 'parentComment', targetEntity: MoreComment::class, cascade: ['persist', 'remove'])]
    private $moreComments;

    #[ORM\Column(type: 'text')]
    private $jsonData;

    #[ORM\Column(type: 'boolean', nullable: true)]
    private $hasReplies;

    #[ORM\Column(type: 'string', length: 15, nullable: true)]
    private $parentCommentRedditId;

    #[ORM\ManyToOne(inversedBy: 'comments')]
    private ?FlairText $flairText = null;

    public function __construct()
    {
        $this->replies = new ArrayCollection();
        $this->commentAuthorTexts = new ArrayCollection();
        $this->commentAwards = new ArrayCollection();
        $this->moreComments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getRedditId(): ?string
    {
        return $this->redditId;
    }

    public function setRedditId(string $redditId): self
    {
        $this->redditId = $redditId;

        return $this;
    }

    public function getParentComment(): ?self
    {
        return $this->parentComment;
    }

    public function setParentComment(?self $parentComment): self
    {
        $this->parentComment = $parentComment;

        return $this;
    }

    /**
     * @return Collection<int, self>
     */
    public function getReplies(): Collection
    {
        return $this->replies;
    }

    public function addReply(self $reply): self
    {
        if (!$this->replies->contains($reply)) {
            $this->replies[] = $reply;
            $reply->setParentComment($this);
        }

        return $this;
    }

    public function removeReply(self $reply): self
    {
        if ($this->replies->removeElement($reply)) {
            // set the owning side to null (unless already changed)
            if ($reply->getParentComment() === $this) {
                $reply->setParentComment(null);
            }
        }

        return $this;
    }

    public function getParentPost(): ?Post
    {
        return $this->parentPost;
    }

    public function setParentPost(?Post $parentPost): self
    {
        $this->parentPost = $parentPost;

        return $this;
    }

    public function getDepth(): ?int
    {
        return $this->depth;
    }

    public function setDepth(int $depth): self
    {
        $this->depth = $depth;

        return $this;
    }

    public function getContent(): ?Content
    {
        return $this->content;
    }

    public function setContent(?Content $content): self
    {
        // unset the owning side of the relation if necessary
        if ($content === null && $this->content !== null) {
            $this->content->setComment(null);
        }

        // set the owning side of the relation if necessary
        if ($content !== null && $content->getComment() !== $this) {
            $content->setComment($this);
        }

        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection<int, CommentAuthorText>
     */
    public function getCommentAuthorTexts(): Collection
    {
        return $this->commentAuthorTexts;
    }

    public function addCommentAuthorText(CommentAuthorText $commentAuthorText): self
    {
        if (!$this->commentAuthorTexts->contains($commentAuthorText)) {
            $this->commentAuthorTexts[] = $commentAuthorText;
            $commentAuthorText->setComment($this);
        }

        return $this;
    }

    public function removeCommentAuthorText(CommentAuthorText $commentAuthorText): self
    {
        if ($this->commentAuthorTexts->removeElement($commentAuthorText)) {
            // set the owning side to null (unless already changed)
            if ($commentAuthorText->getComment() === $this) {
                $commentAuthorText->setComment(null);
            }
        }

        return $this;
    }

    /**
     * Retrieve the latest/current revision of this Comment's Comment Author
     * Text entity.
     *
     * @return CommentAuthorText
     */
    public function getLatestCommentAuthorText(): CommentAuthorText
    {
        return $this->getCommentAuthorTexts()
            ->matching(CommentRepository::createLatestCommentAuthorTextCriteria())
            ->first()
        ;
    }

    /**
     * @return Collection<int, CommentAward>
     */
    public function getCommentAwards(): Collection
    {
        return $this->commentAwards;
    }

    public function addCommentAward(CommentAward $commentAward): self
    {
        if (!$this->commentAwards->contains($commentAward)) {
            $this->commentAwards[] = $commentAward;
            $commentAward->setComment($this);
        }

        return $this;
    }

    public function removeCommentAward(CommentAward $commentAward): self
    {
        if ($this->commentAwards->removeElement($commentAward)) {
            // set the owning side to null (unless already changed)
            if ($commentAward->getComment() === $this) {
                $commentAward->setComment(null);
            }
        }

        return $this;
    }

    /**
     * Loop through this Comment's Comment Awards and sum together the counts for
     * each Award, if any, and return the total.
     *
     * @return int
     */
    public function getCommentAwardsTrueCount(): int
    {
        $count = 0;
        foreach ($this->getCommentAwards() as $postAward) {
            $count += $postAward->getCount();
        }

        return $count;
    }

    /**
     * Search for an existing Comment Author Text that is associated to an Author
     * Text containing the provided `text`.
     *
     * @param  string  $text
     *
     * @return CommentAuthorText|null
     */
    public function getCommentAuthorTextByText(string $text): ?CommentAuthorText
    {
        foreach ($this->getCommentAuthorTexts() as $postAuthorText) {
            if ($postAuthorText->getAuthorText()->getText() === $text) {
                return $postAuthorText;
            }
        }

        return null;
    }

    public function getRedditUrl(): ?string
    {
        return $this->redditUrl;
    }

    public function setRedditUrl(string $redditUrl): self
    {
        $this->redditUrl = $redditUrl;

        return $this;
    }

    /**
     * @return Collection<int, MoreComment>
     */
    public function getMoreComments(): Collection
    {
        return $this->moreComments;
    }

    public function addMoreComment(MoreComment $moreComment): self
    {
        if (!$this->moreComments->contains($moreComment)) {
            $this->moreComments[] = $moreComment;
            $moreComment->setParentComment($this);
        }

        return $this;
    }

    public function removeMoreComment(MoreComment $moreComment): self
    {
        if ($this->moreComments->removeElement($moreComment)) {
            // set the owning side to null (unless already changed)
            if ($moreComment->getParentComment() === $this) {
                $moreComment->setParentComment(null);
            }
        }

        return $this;
    }

    /**
     * Climb the current Comment's tree to find and return, if any, the root
     * Parent Comment.
     *
     * If the current Comment is already a top-level Comment (no Parent
     * Comment), then return null to indicate so.
     *
     * @return Comment|null
     */
    public function getRootComment(): ?Comment
    {
        $parentComment = $this->getParentComment();
        if (empty($parentComment)) {
            return null;
        }

        $rootComment = $parentComment;
        while ($parentComment instanceof Comment) {
            $parentComment = $parentComment->getParentComment();

            if ($parentComment instanceof Comment) {
                $rootComment = $parentComment;
            }
        }

        return $rootComment;
    }

src/templates/components/archive_search.html.twig
<div {{ attributes }}>

    <div class="row">
        <div class="col">
            {{ form_start(computed.searchForm) }}
            <div class="my-custom-class-for-errors">
                {{ form_errors(computed.searchForm) }}
            </div>

            <div class="row">
                <div class="col">
                    <div class="search-form form-control mb-3">
                        <div class="row">
                            <div>
                                {{ form_widget(computed.searchForm.query) }}

                                <small>{{ form_help(computed.searchForm.query) }}</small>

                                <div class="form-error">
                                    {{ form_errors(computed.searchForm.query) }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-4 mt-3">
                                {{ form_widget(computed.searchForm.subreddits) }}

                                <small>{{ form_help(computed.searchForm.subreddits) }}</small>

                                <div class="form-error">
                                    {{ form_errors(computed.searchForm.subreddits) }}
                                </div>
                            </div>
                            <div class="col-sm-4 mt-3">
                                {{ form_widget(computed.searchForm.flairTexts) }}

                                <small>{{ form_help(computed.searchForm.flairTexts) }}</small>

                                <div class="form-error">
                                    {{ form_errors(computed.searchForm.flairTexts) }}
                                </div>
                            </div>
                            <div class="col-sm-4 mt-3">
                                {{ form_widget(computed.searchForm.tags) }}

                                <small>{{ form_help(computed.searchForm.tags) }}</small>

                                <div class="form-error">
                                    {{ form_errors(computed.searchForm.tags) }}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col mt-3 text-center color--white" data-loading="hide">
                                <h6 class="mb-0">{{ computed.searchResults.total|number_format(0, ',') }} Results</h6>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {{ form_end(computed.searchForm) }}
        </div>
    </div>
    {% set currentPaginator = this.paginator(computed.searchResults.total) %}

    <div class="row">
        <div class="col text-center font-size--36 color--white" data-loading>
            {{ include('icons/loading_icon.html.twig') }}
        </div>
    </div>

    <div class="row">
        <div class="col" data-loading="hide">
        {% if computed.searchResults.total > 0 %}
            {{ include('contents/_pagination.deprecated.html.twig', {
                query: query,
                subreddits: subreddits,
                flairTexts: flairTexts,
                tags: tags,
                perPage: perPage,
                paginator: currentPaginator,
            }) }}
        {% endif %}
        </div>
    </div>

    <div class="row">
        <div class="col" data-loading="hide">
            {{ include('contents/_list.html.twig', {contents: computed.searchResults.results}) }}
        </div>
    </div>

    <div class="row">
        <div class="col" data-loading="hide">
            {% if computed.searchResults.total > 0 %}
                {{ include('contents/_pagination.deprecated.html.twig', {
                    query: query,
                    subreddits: subreddits,
                    flairTexts: flairTexts,
                    tags: tags,
                    perPage: perPage,
                    paginator: currentPaginator,
                }) }}
            {% endif %}
        </div>
    </div>
</div>

src/templates/components/asset_render.html.twig
{% if this.isVideo %}
    <video controls autoplay loop class="w-100 {{ this.customClass }}" src="{{ this.path }}" poster="{{ this.videoPoster }}"></video>
{% else %}
    {% if linkImage %}
        <a href="{{ computed.path }}" target="_blank"><img class="img-fluid {{ this.customClass }}" src="{{ computed.path }}" /></a>
    {% else %}
        <img class="img-fluid {{ this.customClass }}" src="{{ this.path }}" />
    {% endif %}
{% endif %}

src/templates/components/comment_thread.html.twig
<div {{ attributes }}>
    <div style="border-left: 2px solid #dedede; padding-left: 5px; margin-left: 10px;">
        <span style="font-size: 10px; font-weight: bold; color: #1c1c1c">
            <span><i class="fa-solid fa-circle-user"></i></span> {{ comment.author }}
        </span>

        {% if comment.flairText %}
            <span class="font-size--8 badge bg-info">{{ comment.flairText.displayText }}</span>
        {% endif %}

        {% for commentAward in comment.commentAwards %}
            {{ component('asset_render', {
                asset: commentAward.award.iconAsset,
                customClass: "width--16px"
            }) }}
        {% endfor %}

        <div style="font-size: 12px; color: #1c1c1c">{{ comment.latestCommentAuthorText.authorText.textHtml|raw }}</div>

        {{ include('contents/list/_content_footer.html.twig', {
            postScore: comment.score,
            commentsCount: comment.replies.count,
            redditLink: comment.redditUrl
        }) }}

        {{ include('contents/comments/_comment_threads.html.twig', {
            comments: comment.replies,
        }) }}

        {% if not comment.moreComments.isEmpty %}
            <span class="text-secondary fst-italic font-size--10"
                  role="button"
                  data-action="click->live#action"
                  data-action-name="syncLoadMore(redditId={{ comment.moreComments[0].redditId }})"
                  data-loading="action(syncLoadMore)|hide"
            >
                Load More ({{ comment.moreComments|length }})
            </span>

            <span data-loading="action(syncLoadMore)|show">
                {{ include('icons/loading_icon.html.twig') }}
            </span>
        {% endif %}

    </div>
</div>

src/templates/components/comment_threads.html.twig
<div>
    <div class="row">
        <div class="col">
            {{ include('contents/comments/_comments_threads.html.twig', {
                comments: this.comments,
            }) }}
        </div>
    </div>
</div>

src/templates/components/youtube_video_render.html.twig
{% if this.isYoutubeVideo %}
    <iframe id="ytplayer" type="text/html" width="640" height="360"
            src="{{ this.embedUrl }}"
    ></iframe>
{% endif %}